### ISSUE TITLE
若漢字多個讀音僅聲調有別，則轉寫可合併

### ISSUE THREAD

**Issue by skylee03** [DINISHING/name-transliterator#1]
如圖所示，若查詢「上海」，則「Zhiang Hai」會被顯示兩次。建議將兩筆結果合併。
![image](https://github.com/DINISHING/name-transliterator/assets/24489025/1bf13fae-5bc0-4415-8893-88e91e97e6a9)

**Comment by saeziae** [comment]
已修正

![image](https://github.com/DINISHING/name-transliterator/assets/26759054/2a768e1b-b8fc-4068-bd4e-982a75bfe26d)
